---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.50.4:3306/alura_forum 
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 